apiVersion: networking.istio.io/v1alpha3
kind: WorkloadGroup
metadata:
  name: "hello-pi"
  namespace: "pi-namespace"
spec:
  metadata:
    labels:
      app: "hello-pi"
  template:
    serviceAccount: "pi-sa"
    network: ""
