apiVersion: networking.istio.io/v1alpha3
kind: WorkloadGroup
metadata:
  name: "hello-vm"
  namespace: "vm-namespace"
spec:
  metadata:
    labels:
      app: "hello-vm"
  template:
    serviceAccount: "vm-sa"
    network: "vm-network"
